import { createFileRoute, Link, redirect, useNavigate } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { BarChart, Bar, Cell, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useModoAtendimento } from "@/hooks/use-modo-atendimento";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard | Mundo Vem Service Desk" }, { name: "description", content: "Indicadores do Service Desk conforme o perfil de acesso." }, { name: "robots", content: "noindex, follow" }] }),
  beforeLoad: async () => { const { data } = await supabase.auth.getUser(); if (!data.user) throw redirect({ to: "/auth" }); },
  component: DashboardPage,
});

const ENCERRADOS = ["resolvido", "fechado", "cancelado"];
const PERIODOS = [7,15,30,90] as const;
const COR_GRAFICO = "hsl(214 70% 55%)";
const COR_SLA_PRIORIDADE: Record<string,string> = {
  baixa: "hsl(152 28% 62%)",
  media: "hsl(210 38% 65%)",
  alta: "hsl(38 55% 68%)",
  critica: "hsl(4 48% 66%)",
};
type Chamado = { id:string; numero:string; titulo:string; status:string; prioridade:string; criado_em:string; aberto_em:string; resolvido_em:string|null; sla_resolucao_violado:boolean; prazo_resolucao:string|null; sla_pausado:boolean; categoria_id:string|null; atendente_id:string|null; solicitante_id:string; segmento_id:string|null };
type Area = { id:string; nome:string };

function getArea(): Area|null { try { const raw=localStorage.getItem("service_desk_segmento"); if(!raw) return null; const v=JSON.parse(raw); return v?.id ? {id:String(v.id),nome:String(v.nome??"")} : null; } catch { return null; } }
function slaStatus(c:Chamado,now:number){ if(c.sla_pausado)return "pausado"; if(!c.prazo_resolucao)return "sem_sla"; const sec=(new Date(c.prazo_resolucao).getTime()-now)/1000; if(sec<=0)return "vencido"; if(sec<=3600)return "vencendo"; return "ok"; }
function statusLabel(s:string){ return ({aberto:"Aberto",em_andamento:"Em andamento",aguardando_usuario:"Aguardando usuário",aguardando_terceiro:"Aguardando terceiro",resolvido:"Resolvido",fechado:"Fechado",cancelado:"Cancelado"} as Record<string,string>)[s]??s; }
function statusStyle(_s:string){ return "bg-muted text-muted-foreground border border-border"; }
function prioridadeStyle(_p:string){ return "bg-muted text-muted-foreground border border-border"; }

function DashboardPage(){
  const {user}=Route.useRouteContext(); const navigate=useNavigate(); const areaSelecionada=getArea();
  const [now,setNow]=useState(Date.now()); const [dias,setDias]=useState<number>(30); const [filtroStatus,setFiltroStatus]=useState("todos");
  const {data:roles=[],isLoading:loadingRoles}=useQuery({queryKey:["my-roles",user.id],queryFn:async()=>{const {data,error}=await supabase.from("user_roles").select("role").eq("user_id",user.id);if(error)throw error;return(data??[]).map(r=>String(r.role));}});
  const isGestor=roles.includes("gestor")&&!roles.includes("admin");
  const {data:perfilArea}=useQuery({queryKey:["dashboard-profile-area",user.id],enabled:isGestor,queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("area_id").eq("id",user.id).maybeSingle();if(error)throw error;return data as {area_id:string|null}|null;}});
  const {data:areaGestor}=useQuery({queryKey:["dashboard-gestor-area",perfilArea?.area_id],enabled:isGestor&&!!perfilArea?.area_id,queryFn:async()=>{const {data,error}=await supabase.from("areas").select("id,nome,ativo").eq("id",perfilArea!.area_id!).maybeSingle();if(error)throw error;if(!data)return null;const {data:segmentos,error:segError}=await supabase.from("segmentos").select("id,nome").eq("ativo",true).order("ordem").order("nome");if(segError)throw segError;const normalizar=(nome:string)=>nome.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g,"");return (segmentos??[]).find((s)=>normalizar(s.nome)===normalizar(data.nome)) as Area|null;}});
  const area=isGestor?(areaGestor??null):areaSelecionada;
  useEffect(()=>{if(!area && !isGestor) navigate({to:"/areas",replace:true}); const t=window.setInterval(()=>setNow(Date.now()),30000); return()=>window.clearInterval(t);},[area,isGestor,navigate]);
  const isAtendente=roles.includes("atendente");
  const {modo}=useModoAtendimento(user.id,isAtendente);
  const perfil=modo==="colaborador"&&isAtendente?"colaborador":roles.includes("admin")?"admin":roles.includes("gestor")?"gestor":isAtendente?"atendente":"colaborador";
  const isFull=perfil==="admin"||perfil==="gestor"; const since=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-dias);return d.toISOString();},[dias]);
  const {data:chamados=[],isLoading}=useQuery({queryKey:["dashboard-chamados",perfil,user.id,dias,area?.id],enabled:!loadingRoles&&!!area,queryFn:async()=>{let q=(supabase as any).from("chamados").select("id,numero,titulo,status,prioridade,criado_em,aberto_em,resolvido_em,sla_resolucao_violado,prazo_resolucao,sla_pausado,categoria_id,atendente_id,solicitante_id,segmento_id").eq("segmento_id",area!.id).order("criado_em",{ascending:false}); if(isFull)q=q.gte("criado_em",since); if(perfil==="colaborador")q=q.eq("solicitante_id",user.id); if(perfil==="atendente")q=q.or(`atendente_id.eq.${user.id},atendente_id.is.null`); const {data,error}=await q;if(error)throw error;return(data??[]) as Chamado[];}});
  const {data:categorias=[]}=useQuery({queryKey:["dashboard-categorias",area?.id],enabled:!!area,queryFn:async()=>{const {data,error}=await supabase.from("categorias").select("id,nome").eq("ativo",true).eq("segmento_id",area!.id).order("ordem").order("nome");if(error)throw error;return data??[];}});
  const catMap=useMemo(()=>Object.fromEntries(categorias.map((c:any)=>[c.id,c.nome])),[categorias]);
  const active=(c:Chamado)=>!ENCERRADOS.includes(c.status); const resolved=(c:Chamado)=>c.status==="resolvido"||c.status==="fechado";
  const resumo=useMemo(()=>{const base=chamados; const violados=base.filter(c=>c.sla_resolucao_violado||slaStatus(c,now)==="vencido").length; const resolvidos=base.filter(resolved).filter(c=>c.resolvido_em); const dur=resolvidos.map(c=>(new Date(c.resolvido_em!).getTime()-new Date(c.criado_em).getTime())/3600000); return {total:chamados.length,abertosAgora:base.filter(active).length,resolvidos:base.filter(resolved).length,taxaSla:base.length?Math.round(((base.length-violados)/base.length)*100):null,tMedio:dur.length?+(dur.reduce((a,b)=>a+b,0)/dur.length).toFixed(1):null,criticosAbertos:base.filter(c=>c.prioridade==="critica"&&active(c)).length,vencendo:base.filter(c=>slaStatus(c,now)==="vencendo").length,vencidos:base.filter(c=>slaStatus(c,now)==="vencido").length,pausados:base.filter(c=>slaStatus(c,now)==="pausado").length};},[chamados,now]);
  const porCategoria=useMemo(()=>{const base=chamados;const m=new Map<string,number>();base.forEach(c=>{const n=c.categoria_id?catMap[c.categoria_id]??"—":"—";m.set(n,(m.get(n)??0)+1);});return Array.from(m.entries()).map(([categoria,total])=>({categoria,total})).sort((a,b)=>b.total-a.total).slice(0,8);},[chamados,catMap]);
  const recentes=useMemo(()=>{let b=chamados;if(filtroStatus!=="todos")b=b.filter(c=>filtroStatus==="abertos"?c.status==="aberto":filtroStatus==="andamento"?c.status==="em_andamento":resolved(c));return b.slice(0,10);},[chamados,filtroStatus]);
  const volume=useMemo(()=>{if(!isFull)return[];const m=new Map<string,{dia:string;abertos:number;resolvidos:number}>();for(let i=dias-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);m.set(k,{dia:k.slice(5),abertos:0,resolvidos:0});}chamados.forEach(c=>{const a=m.get(c.criado_em.slice(0,10));if(a)a.abertos++;if(c.resolvido_em){const r=m.get(c.resolvido_em.slice(0,10));if(r)r.resolvidos++;}});return Array.from(m.values());},[chamados,dias,isFull]);
  const slaPorPrioridade=useMemo(()=>["baixa","media","alta","critica"].map(p=>{const i=chamados.filter(c=>c.prioridade===p);const v=i.filter(c=>c.sla_resolucao_violado||slaStatus(c,now)==="vencido").length;return{prioridade:p,taxa_pct:i.length?Math.round(((i.length-v)/i.length)*100):0};}),[chamados,now]);
  if(!area||loadingRoles||(isGestor&&!areaGestor)||isLoading)return <div className="p-8 text-center text-sm text-muted-foreground">Carregando dashboard…</div>;
  if(perfil==="colaborador")return <CollaboratorDashboard area={area} resumo={resumo} porCategoria={porCategoria} slaPorPrioridade={slaPorPrioridade}/>;
  if(perfil==="atendente")return <AttendantDashboard area={area} resumo={resumo} porCategoria={porCategoria}/>;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">Dashboard Gerencial — {area.nome}</h1><p className="text-sm text-muted-foreground">{perfil==="gestor"?"Métricas somente dos chamados da sua equipe nesta área.":"Métricas da área selecionada."}</p></div><div className="flex gap-2">{PERIODOS.map(d=><Button key={d} size="sm" variant={dias===d?"default":"outline"} onClick={()=>setDias(d)}>{d}d</Button>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Kpi label="Total chamados" valor={resumo.total}/><Kpi label="Abertos agora" valor={resumo.abertosAgora}/><Kpi label="Resolvidos" valor={resumo.resolvidos}/><Kpi label="Taxa SLA" valor={resumo.taxaSla!==null?`${resumo.taxaSla}%`:"—"} destaque={resumo.taxaSla!==null&&resumo.taxaSla>=80}/><Kpi label="T. médio resolução" valor={resumo.tMedio!==null?(resumo.tMedio<1?`${Math.round(resumo.tMedio*60)}min`:`${resumo.tMedio}h`):"—"}/><Kpi label="Críticos abertos" valor={resumo.criticosAbertos}/><Kpi label="SLA vencendo" valor={resumo.vencendo}/><Kpi label="SLA vencido" valor={resumo.vencidos}/><Kpi label="SLA pausado" valor={resumo.pausados}/></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Volume de chamados</CardTitle><p className="text-xs text-muted-foreground">Aberturas e resoluções no período selecionado.</p></CardHeader><CardContent><ResponsiveContainer width="100%" height={220}><LineChart data={volume}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="dia" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="abertos" stroke={COR_GRAFICO} strokeWidth={2} name="Abertos"/><Line type="monotone" dataKey="resolvidos" stroke="hsl(var(--muted-foreground))" strokeWidth={2} name="Resolvidos"/></LineChart></ResponsiveContainer></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Desempenho de SLA</CardTitle><p className="text-xs text-muted-foreground">Percentual de chamados dentro do prazo.</p></CardHeader><CardContent><ResponsiveContainer width="100%" height={220}><BarChart data={slaPorPrioridade}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="prioridade" tick={{fontSize:10}}/><YAxis unit="%" domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="taxa_pct" name="Taxa SLA" radius={[4,4,0,0]}>{slaPorPrioridade.map((item)=><Cell key={item.prioridade} fill={COR_SLA_PRIORIDADE[item.prioridade]}/>)}</Bar></BarChart></ResponsiveContainer></CardContent></Card></div>
    <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Chamados por categoria</CardTitle><p className="text-xs text-muted-foreground">Onde está concentrado o volume de atendimento.</p></CardHeader><CardContent><ResponsiveContainer width="100%" height={240}><BarChart data={porCategoria} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="categoria" type="category" width={130}/><Tooltip/><Bar dataKey="total" fill={COR_GRAFICO} name="Total" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></CardContent></Card>
    <Recentes recentes={recentes} catMap={catMap} filtroStatus={filtroStatus} setFiltroStatus={setFiltroStatus}/>
  </div>;
}

function CollaboratorDashboard({area,resumo,porCategoria,slaPorPrioridade}:{area:Area;resumo:any;porCategoria:any[];slaPorPrioridade:any[]}){return <div className="space-y-4"><div><h1 className="text-2xl font-bold">Meu Dashboard — {area.nome}</h1><p className="text-sm text-muted-foreground">Visão geral dos seus chamados nesta área.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Total chamados" valor={resumo.total}/><Kpi label="Abertos agora" valor={resumo.abertosAgora}/><Kpi label="Resolvidos" valor={resumo.resolvidos}/><Kpi label="Taxa SLA" valor={resumo.taxaSla!==null?`${resumo.taxaSla}%`:"—"}/></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Chamados por categoria</CardTitle><p className="text-xs text-muted-foreground">Distribuição dos seus chamados.</p></CardHeader><CardContent><ResponsiveContainer width="100%" height={240}><BarChart data={porCategoria} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="categoria" type="category" width={130}/><Tooltip/><Bar dataKey="total" fill={COR_GRAFICO} name="Total" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Desempenho de SLA</CardTitle><p className="text-xs text-muted-foreground">Percentual dentro do prazo por prioridade.</p></CardHeader><CardContent><ResponsiveContainer width="100%" height={240}><BarChart data={slaPorPrioridade}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="prioridade"/><YAxis unit="%" domain={[0,100]}/><Tooltip/><Bar dataKey="taxa_pct" fill={COR_GRAFICO} name="Taxa SLA" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card></div></div>}
function AttendantDashboard({area,resumo,porCategoria}:{area:Area;resumo:any;porCategoria:any[]}){return <div className="space-y-4"><div><h1 className="text-2xl font-bold">Meu Dashboard — {area.nome}</h1><p className="text-sm text-muted-foreground">Chamados atribuídos a você ou ainda sem atendente nesta área.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Total chamados" valor={resumo.total}/><Kpi label="Abertos agora" valor={resumo.abertosAgora}/><Kpi label="Resolvidos" valor={resumo.resolvidos}/><Kpi label="Taxa SLA" valor={resumo.taxaSla!==null?`${resumo.taxaSla}%`:"—"}/></div><Card><CardHeader className="pb-2"><CardTitle className="text-sm">Chamados por categoria</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={240}><BarChart data={porCategoria} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="categoria" type="category" width={130}/><Tooltip/><Bar dataKey="total" fill={COR_GRAFICO} name="Total" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></CardContent></Card></div>}
function Kpi({label,valor,destaque=false}:{label:string;valor:any;destaque?:boolean}){return <Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">{label}</div><div className={`mt-1 text-2xl font-bold ${destaque?"text-emerald-600":""}`}>{valor}</div></CardContent></Card>}
function Recentes({recentes,catMap,filtroStatus,setFiltroStatus}:{recentes:Chamado[];catMap:Record<string,string>;filtroStatus:string;setFiltroStatus:(v:string)=>void}){return <Card><CardHeader className="flex flex-row items-center justify-between gap-2"><CardTitle className="text-sm">Chamados recentes</CardTitle><p className="text-xs text-muted-foreground">Acesse rapidamente os últimos atendimentos.</p><div className="flex gap-1"><Button size="sm" variant={filtroStatus==="todos"?"default":"outline"} onClick={()=>setFiltroStatus("todos")}>Todos</Button><Button size="sm" variant={filtroStatus==="abertos"?"default":"outline"} onClick={()=>setFiltroStatus("abertos")}>Abertos</Button><Button size="sm" variant={filtroStatus==="andamento"?"default":"outline"} onClick={()=>setFiltroStatus("andamento")}>Em andamento</Button><Button size="sm" variant={filtroStatus==="resolvidos"?"default":"outline"} onClick={()=>setFiltroStatus("resolvidos")}>Resolvidos</Button></div></CardHeader><CardContent className="p-0"><div className="divide-y">{recentes.map(c=><Link key={c.id} to="/chamados/$id" params={{id:c.id}} className="flex items-center justify-between gap-3 p-4 hover:bg-muted/40"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-mono text-xs text-muted-foreground">{c.numero}</span><Badge className={prioridadeStyle(c.prioridade)}>{c.prioridade}</Badge><Badge className={statusStyle(c.status)}>{statusLabel(c.status)}</Badge></div><div className="truncate font-medium">{c.titulo}</div><div className="text-xs text-muted-foreground">{c.categoria_id?catMap[c.categoria_id]??"—":"—"} • {new Date(c.criado_em).toLocaleString("pt-BR")}</div></div></Link>)}</div></CardContent></Card>}
