import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Network, Plus, X, Eye, Pencil, Trash2 } from "lucide-react";
export const Route = createFileRoute("/_authenticated/itsm-servicos")({ component: ItsmServicos });
const statusLabel: Record<string,string>={ativo:"Ativo",inativo:"Inativo"};
function ItsmServicos(){const qc=useQueryClient();const [open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[selected,setSelected]=useState<any>(null),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);const [nome,setNome]=useState(""),[descricao,setDescricao]=useState(""),[status,setStatus]=useState("ativo"),[segmento,setSegmento]=useState("");
const {data,isLoading}=useQuery({queryKey:["itsm-servicos"],queryFn:async()=>{const {data,error}=await supabase.from("itsm_servicos").select("*,segmentos(id,nome)").order("nome");if(error)throw error;return data??[]}});const {data:segmentos}=useQuery({queryKey:["itsm-servicos-segmentos"],queryFn:async()=>{const {data,error}=await supabase.from("segmentos").select("id,nome").eq("ativo",true).order("nome");if(error)throw error;return data??[]}});
const reset=()=>{setNome("");setDescricao("");setStatus("ativo");setSegmento("");setError(null)};const load=(x:any)=>{setNome(x.nome??"");setDescricao(x.descricao??"");setStatus(x.status??"ativo");setSegmento(x.segmento_id??"");setError(null)};const save=async()=>{if(!nome.trim())return setError("Informe o nome do serviço.");setSaving(true);setError(null);const {data:u}=await supabase.auth.getUser();const p={nome:nome.trim(),descricao:descricao.trim()||null,status,segmento_id:segmento||null,atualizado_em:new Date().toISOString(),...(editing?{}:{criado_por:u.user?.id??null})};const r=editing?await supabase.from("itsm_servicos").update(p).eq("id",editing.id).select("*,segmentos(id,nome)").single():await supabase.from("itsm_servicos").insert(p).select("*,segmentos(id,nome)").single();setSaving(false);if(r.error)return setError(r.error.code==="23505"?"Já existe um serviço com este nome.":r.error.message);setSelected(r.data);setEditing(null);setOpen(false);reset();await qc.invalidateQueries({queryKey:["itsm-servicos"]});};const remove=async()=>{if(!selected||!confirm(`Excluir o serviço "${selected.nome}"?`))return;const r=await supabase.from("itsm_servicos").delete().eq("id",selected.id);if(r.error)return setError(r.error.message);setSelected(null);await qc.invalidateQueries({queryKey:["itsm-servicos"]})};const openEdit=(x:any)=>{load(x);setEditing(x);setOpen(true)};
return <div className="space-y-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Network className="h-6 w-6 text-primary"/><h1 className="text-2xl font-semibold tracking-tight">Serviços</h1></div><p className="text-sm text-muted-foreground">Gestão dos serviços de TI e negócio e seus vínculos na CMDB.</p></div><Button onClick={()=>{reset();setEditing(null);setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Novo serviço</Button></div>
{(open||editing)&&<Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{editing?"Editar serviço":"Novo serviço"}</CardTitle><Button variant="ghost" size="icon" onClick={()=>{setOpen(false);setEditing(null)}}><X className="h-4 w-4"/></Button></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Nome *</Label><Input value={nome} onChange={e=>setNome(e.target.value)}/></div><div className="space-y-2"><Label>Status</Label><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ativo">Ativo</SelectItem><SelectItem value="inativo">Inativo</SelectItem></SelectContent></Select></div><div className="space-y-2 md:col-span-2"><Label>Descrição</Label><Textarea value={descricao} onChange={e=>setDescricao(e.target.value)}/></div><div className="space-y-2"><Label>Segmento</Label><Select value={segmento||"none"} onValueChange={v=>setSegmento(v==="none"?"":v)}><SelectTrigger><SelectValue placeholder="Sem segmento"/></SelectTrigger><SelectContent><SelectItem value="none">Sem segmento</SelectItem>{(segmentos??[]).map((s:any)=><SelectItem key={s.id} value={s.id}>{s.nome}</SelectItem>)}</SelectContent></Select></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>{setOpen(false);setEditing(null)}}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Salvando...":"Salvar"}</Button></div></CardContent></Card>}
{selected&&!editing&&<Card className="border-primary/50 ring-1 ring-primary/20"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Eye className="h-5 w-5"/>{selected.nome}</CardTitle><p className="text-sm text-muted-foreground">Detalhes do serviço</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>openEdit(selected)}><Pencil className="mr-2 h-4 w-4"/>Editar</Button><Button variant="destructive" size="sm" onClick={remove}><Trash2 className="mr-2 h-4 w-4"/>Excluir</Button><Button variant="ghost" size="icon" onClick={()=>setSelected(null)}><X className="h-4 w-4"/></Button></div></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-3"><Detail l="Status" v={statusLabel[selected.status]??selected.status}/><Detail l="Segmento" v={selected.segmentos?.nome}/><Detail l="ID" v={selected.id}/></div><Detail l="Descrição" v={selected.descricao}/></CardContent></Card>}
<Card><CardHeader><CardTitle>Serviços registrados</CardTitle></CardHeader><CardContent>{isLoading?<p className="text-sm text-muted-foreground">Carregando...</p>:data?.length?<div className="space-y-3">{data.map((x:any)=><div key={x.id} className="flex items-center justify-between gap-4 rounded-lg border p-4"><div><div className="font-medium">{x.nome}</div><div className="text-sm text-muted-foreground">{x.segmentos?.nome??"Sem segmento"} · {statusLabel[x.status]??x.status}</div></div><Button variant="outline" size="sm" onClick={()=>setSelected(x)}><Eye className="mr-2 h-4 w-4"/>Ver detalhes</Button></div>)}</div>:<p className="text-sm text-muted-foreground">Nenhum serviço cadastrado.</p>}</CardContent></Card></div>}
function Detail({l,v}:{l:string,v:any}){return <div><div className="text-xs font-medium text-muted-foreground">{l}</div><div className="text-sm">{v==null||v===""?"-":String(v)}</div></div>}
