/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistenteRouteImport } from './routes/api/assistente'
import { Route as AuthenticatedItsmServicosRouteImport } from './routes/_authenticated/itsm-servicos'
import { Route as AuthenticatedItsmRelacionamentosRouteImport } from './routes/_authenticated/itsm-relacionamentos'
import { Route as AuthenticatedItsmProblemasRouteImport } from './routes/_authenticated/itsm-problemas'
import { Route as AuthenticatedItsmMudancasRouteImport } from './routes/_authenticated/itsm-mudancas'
import { Route as AuthenticatedItsmGovernancaRouteImport } from './routes/_authenticated/itsm-governanca'
import { Route as AuthenticatedItsmConhecimentoRouteImport } from './routes/_authenticated/itsm-conhecimento'
import { Route as AuthenticatedItsmAvancadoRouteImport } from './routes/_authenticated/itsm-avancado'
import { Route as AuthenticatedItsmAuditoriaRouteImport } from './routes/_authenticated/itsm-auditoria'
import { Route as AuthenticatedItsmAtivosRouteImport } from './routes/_authenticated/itsm-ativos'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedChamadosIndexRouteImport } from './routes/_authenticated/chamados.index'
import { Route as AuthenticatedBaseConhecimentoIndexRouteImport } from './routes/_authenticated/base-conhecimento.index'
import { Route as AuthenticatedAssistenteIndexRouteImport } from './routes/_authenticated/assistente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedChamadosNovoRouteImport } from './routes/_authenticated/chamados.novo'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'
import { Route as AuthenticatedBaseConhecimentoNovoRouteImport } from './routes/_authenticated/base-conhecimento.novo'
import { Route as AuthenticatedBaseConhecimentoIdRouteImport } from './routes/_authenticated/base-conhecimento.$id'
import { Route as AuthenticatedAssistenteConversaIdRouteImport } from './routes/_authenticated/assistente.$conversaId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTiposChamadoRouteImport } from './routes/_authenticated/admin.tipos-chamado'
import { Route as AuthenticatedAdminSegmentosRouteImport } from './routes/_authenticated/admin/segmentos'
import { Route as AuthenticatedAdminRegrasAtribuicaoRouteImport } from './routes/_authenticated/admin/regras-atribuicao'
import { Route as AuthenticatedAdminItsmPermissoesRouteImport } from './routes/_authenticated/admin/itsm-permissoes'
import { Route as AuthenticatedAdminGruposRouteImport } from './routes/_authenticated/admin/grupos'
import { Route as AuthenticatedAdminDocumentacaoRouteImport } from './routes/_authenticated/admin/documentacao'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated/admin.catalogo'
import { Route as AuthenticatedAdminAutomacoesRouteImport } from './routes/_authenticated/admin/automacoes'
import { Route as AuthenticatedAdminAssistenteRouteImport } from './routes/_authenticated/admin.assistente'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedBaseConhecimentoIdEditarRouteImport } from './routes/_authenticated/base-conhecimento.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistenteRoute = ApiAssistenteRouteImport.update({
  id: '/api/assistente',
  path: '/api/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedItsmServicosRoute =
  AuthenticatedItsmServicosRouteImport.update({
    id: '/itsm-servicos',
    path: '/itsm-servicos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmRelacionamentosRoute =
  AuthenticatedItsmRelacionamentosRouteImport.update({
    id: '/itsm-relacionamentos',
    path: '/itsm-relacionamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmProblemasRoute =
  AuthenticatedItsmProblemasRouteImport.update({
    id: '/itsm-problemas',
    path: '/itsm-problemas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmMudancasRoute =
  AuthenticatedItsmMudancasRouteImport.update({
    id: '/itsm-mudancas',
    path: '/itsm-mudancas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmGovernancaRoute =
  AuthenticatedItsmGovernancaRouteImport.update({
    id: '/itsm-governanca',
    path: '/itsm-governanca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmConhecimentoRoute =
  AuthenticatedItsmConhecimentoRouteImport.update({
    id: '/itsm-conhecimento',
    path: '/itsm-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmAvancadoRoute =
  AuthenticatedItsmAvancadoRouteImport.update({
    id: '/itsm-avancado',
    path: '/itsm-avancado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmAuditoriaRoute =
  AuthenticatedItsmAuditoriaRouteImport.update({
    id: '/itsm-auditoria',
    path: '/itsm-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItsmAtivosRoute = AuthenticatedItsmAtivosRouteImport.update({
  id: '/itsm-ativos',
  path: '/itsm-ativos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChamadosIndexRoute =
  AuthenticatedChamadosIndexRouteImport.update({
    id: '/chamados/',
    path: '/chamados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIndexRoute =
  AuthenticatedBaseConhecimentoIndexRouteImport.update({
    id: '/base-conhecimento/',
    path: '/base-conhecimento/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteIndexRoute =
  AuthenticatedAssistenteIndexRouteImport.update({
    id: '/assistente/',
    path: '/assistente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChamadosNovoRoute =
  AuthenticatedChamadosNovoRouteImport.update({
    id: '/chamados/novo',
    path: '/chamados/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoNovoRoute =
  AuthenticatedBaseConhecimentoNovoRouteImport.update({
    id: '/base-conhecimento/novo',
    path: '/base-conhecimento/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIdRoute =
  AuthenticatedBaseConhecimentoIdRouteImport.update({
    id: '/base-conhecimento/$id',
    path: '/base-conhecimento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteConversaIdRoute =
  AuthenticatedAssistenteConversaIdRouteImport.update({
    id: '/assistente/$conversaId',
    path: '/assistente/$conversaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTiposChamadoRoute =
  AuthenticatedAdminTiposChamadoRouteImport.update({
    id: '/admin/tipos-chamado',
    path: '/admin/tipos-chamado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSegmentosRoute =
  AuthenticatedAdminSegmentosRouteImport.update({
    id: '/admin/segmentos',
    path: '/admin/segmentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRegrasAtribuicaoRoute =
  AuthenticatedAdminRegrasAtribuicaoRouteImport.update({
    id: '/admin/regras-atribuicao',
    path: '/admin/regras-atribuicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminItsmPermissoesRoute =
  AuthenticatedAdminItsmPermissoesRouteImport.update({
    id: '/admin/itsm-permissoes',
    path: '/admin/itsm-permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGruposRoute =
  AuthenticatedAdminGruposRouteImport.update({
    id: '/admin/grupos',
    path: '/admin/grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentacaoRoute =
  AuthenticatedAdminDocumentacaoRouteImport.update({
    id: '/admin/documentacao',
    path: '/admin/documentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAutomacoesRoute =
  AuthenticatedAdminAutomacoesRouteImport.update({
    id: '/admin/automacoes',
    path: '/admin/automacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssistenteRoute =
  AuthenticatedAdminAssistenteRouteImport.update({
    id: '/admin/assistente',
    path: '/admin/assistente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBaseConhecimentoIdEditarRoute =
  AuthenticatedBaseConhecimentoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedBaseConhecimentoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/itsm-ativos': typeof AuthenticatedItsmAtivosRoute
  '/itsm-auditoria': typeof AuthenticatedItsmAuditoriaRoute
  '/itsm-avancado': typeof AuthenticatedItsmAvancadoRoute
  '/itsm-conhecimento': typeof AuthenticatedItsmConhecimentoRoute
  '/itsm-governanca': typeof AuthenticatedItsmGovernancaRoute
  '/itsm-mudancas': typeof AuthenticatedItsmMudancasRoute
  '/itsm-problemas': typeof AuthenticatedItsmProblemasRoute
  '/itsm-relacionamentos': typeof AuthenticatedItsmRelacionamentosRoute
  '/itsm-servicos': typeof AuthenticatedItsmServicosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/documentacao': typeof AuthenticatedAdminDocumentacaoRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/admin/itsm-permissoes': typeof AuthenticatedAdminItsmPermissoesRoute
  '/admin/regras-atribuicao': typeof AuthenticatedAdminRegrasAtribuicaoRoute
  '/admin/segmentos': typeof AuthenticatedAdminSegmentosRoute
  '/admin/tipos-chamado': typeof AuthenticatedAdminTiposChamadoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/itsm-ativos': typeof AuthenticatedItsmAtivosRoute
  '/itsm-auditoria': typeof AuthenticatedItsmAuditoriaRoute
  '/itsm-avancado': typeof AuthenticatedItsmAvancadoRoute
  '/itsm-conhecimento': typeof AuthenticatedItsmConhecimentoRoute
  '/itsm-governanca': typeof AuthenticatedItsmGovernancaRoute
  '/itsm-mudancas': typeof AuthenticatedItsmMudancasRoute
  '/itsm-problemas': typeof AuthenticatedItsmProblemasRoute
  '/itsm-relacionamentos': typeof AuthenticatedItsmRelacionamentosRoute
  '/itsm-servicos': typeof AuthenticatedItsmServicosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/documentacao': typeof AuthenticatedAdminDocumentacaoRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/admin/itsm-permissoes': typeof AuthenticatedAdminItsmPermissoesRoute
  '/admin/regras-atribuicao': typeof AuthenticatedAdminRegrasAtribuicaoRoute
  '/admin/segmentos': typeof AuthenticatedAdminSegmentosRoute
  '/admin/tipos-chamado': typeof AuthenticatedAdminTiposChamadoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/assistente': typeof AuthenticatedAssistenteIndexRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/itsm-ativos': typeof AuthenticatedItsmAtivosRoute
  '/_authenticated/itsm-auditoria': typeof AuthenticatedItsmAuditoriaRoute
  '/_authenticated/itsm-avancado': typeof AuthenticatedItsmAvancadoRoute
  '/_authenticated/itsm-conhecimento': typeof AuthenticatedItsmConhecimentoRoute
  '/_authenticated/itsm-governanca': typeof AuthenticatedItsmGovernancaRoute
  '/_authenticated/itsm-mudancas': typeof AuthenticatedItsmMudancasRoute
  '/_authenticated/itsm-problemas': typeof AuthenticatedItsmProblemasRoute
  '/_authenticated/itsm-relacionamentos': typeof AuthenticatedItsmRelacionamentosRoute
  '/_authenticated/itsm-servicos': typeof AuthenticatedItsmServicosRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/assistente': typeof AuthenticatedAdminAssistenteRoute
  '/_authenticated/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/documentacao': typeof AuthenticatedAdminDocumentacaoRoute
  '/_authenticated/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/_authenticated/admin/itsm-permissoes': typeof AuthenticatedAdminItsmPermissoesRoute
  '/_authenticated/admin/regras-atribuicao': typeof AuthenticatedAdminRegrasAtribuicaoRoute
  '/_authenticated/admin/segmentos': typeof AuthenticatedAdminSegmentosRoute
  '/_authenticated/admin/tipos-chamado': typeof AuthenticatedAdminTiposChamadoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/assistente/$conversaId': typeof AuthenticatedAssistenteConversaIdRoute
  '/_authenticated/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/_authenticated/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/_authenticated/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/assistente/': typeof AuthenticatedAssistenteIndexRoute
  '/_authenticated/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/_authenticated/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/_authenticated/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/areas'
    | '/catalogo'
    | '/dashboard'
    | '/fila'
    | '/gestao'
    | '/itsm-ativos'
    | '/itsm-auditoria'
    | '/itsm-avancado'
    | '/itsm-conhecimento'
    | '/itsm-governanca'
    | '/itsm-mudancas'
    | '/itsm-problemas'
    | '/itsm-relacionamentos'
    | '/itsm-servicos'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assistente'
    | '/admin/automacoes'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/documentacao'
    | '/admin/grupos'
    | '/admin/itsm-permissoes'
    | '/admin/regras-atribuicao'
    | '/admin/segmentos'
    | '/admin/tipos-chamado'
    | '/admin/usuarios'
    | '/assistente/$conversaId'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/admin/'
    | '/assistente/'
    | '/base-conhecimento/'
    | '/chamados/'
    | '/base-conhecimento/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/areas'
    | '/catalogo'
    | '/dashboard'
    | '/fila'
    | '/gestao'
    | '/itsm-ativos'
    | '/itsm-auditoria'
    | '/itsm-avancado'
    | '/itsm-conhecimento'
    | '/itsm-governanca'
    | '/itsm-mudancas'
    | '/itsm-problemas'
    | '/itsm-relacionamentos'
    | '/itsm-servicos'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assistente'
    | '/admin/automacoes'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/documentacao'
    | '/admin/grupos'
    | '/admin/itsm-permissoes'
    | '/admin/regras-atribuicao'
    | '/admin/segmentos'
    | '/admin/tipos-chamado'
    | '/admin/usuarios'
    | '/assistente/$conversaId'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/admin'
    | '/assistente'
    | '/base-conhecimento'
    | '/chamados'
    | '/base-conhecimento/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/areas'
    | '/_authenticated/catalogo'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/_authenticated/gestao'
    | '/_authenticated/itsm-ativos'
    | '/_authenticated/itsm-auditoria'
    | '/_authenticated/itsm-avancado'
    | '/_authenticated/itsm-conhecimento'
    | '/_authenticated/itsm-governanca'
    | '/_authenticated/itsm-mudancas'
    | '/_authenticated/itsm-problemas'
    | '/_authenticated/itsm-relacionamentos'
    | '/_authenticated/itsm-servicos'
    | '/api/assistente'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/assistente'
    | '/_authenticated/admin/automacoes'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/documentacao'
    | '/_authenticated/admin/grupos'
    | '/_authenticated/admin/itsm-permissoes'
    | '/_authenticated/admin/regras-atribuicao'
    | '/_authenticated/admin/segmentos'
    | '/_authenticated/admin/tipos-chamado'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/assistente/$conversaId'
    | '/_authenticated/base-conhecimento/$id'
    | '/_authenticated/base-conhecimento/novo'
    | '/_authenticated/chamados/$id'
    | '/_authenticated/chamados/novo'
    | '/_authenticated/admin/'
    | '/_authenticated/assistente/'
    | '/_authenticated/base-conhecimento/'
    | '/_authenticated/chamados/'
    | '/_authenticated/base-conhecimento/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAssistenteRoute: typeof ApiAssistenteRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistente': {
      id: '/api/assistente'
      path: '/api/assistente'
      fullPath: '/api/assistente'
      preLoaderRoute: typeof ApiAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/itsm-servicos': {
      id: '/_authenticated/itsm-servicos'
      path: '/itsm-servicos'
      fullPath: '/itsm-servicos'
      preLoaderRoute: typeof AuthenticatedItsmServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-relacionamentos': {
      id: '/_authenticated/itsm-relacionamentos'
      path: '/itsm-relacionamentos'
      fullPath: '/itsm-relacionamentos'
      preLoaderRoute: typeof AuthenticatedItsmRelacionamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-problemas': {
      id: '/_authenticated/itsm-problemas'
      path: '/itsm-problemas'
      fullPath: '/itsm-problemas'
      preLoaderRoute: typeof AuthenticatedItsmProblemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-mudancas': {
      id: '/_authenticated/itsm-mudancas'
      path: '/itsm-mudancas'
      fullPath: '/itsm-mudancas'
      preLoaderRoute: typeof AuthenticatedItsmMudancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-governanca': {
      id: '/_authenticated/itsm-governanca'
      path: '/itsm-governanca'
      fullPath: '/itsm-governanca'
      preLoaderRoute: typeof AuthenticatedItsmGovernancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-conhecimento': {
      id: '/_authenticated/itsm-conhecimento'
      path: '/itsm-conhecimento'
      fullPath: '/itsm-conhecimento'
      preLoaderRoute: typeof AuthenticatedItsmConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-avancado': {
      id: '/_authenticated/itsm-avancado'
      path: '/itsm-avancado'
      fullPath: '/itsm-avancado'
      preLoaderRoute: typeof AuthenticatedItsmAvancadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-auditoria': {
      id: '/_authenticated/itsm-auditoria'
      path: '/itsm-auditoria'
      fullPath: '/itsm-auditoria'
      preLoaderRoute: typeof AuthenticatedItsmAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itsm-ativos': {
      id: '/_authenticated/itsm-ativos'
      path: '/itsm-ativos'
      fullPath: '/itsm-ativos'
      preLoaderRoute: typeof AuthenticatedItsmAtivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chamados/': {
      id: '/_authenticated/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof AuthenticatedChamadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/': {
      id: '/_authenticated/base-conhecimento/'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento/'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente/': {
      id: '/_authenticated/assistente/'
      path: '/assistente'
      fullPath: '/assistente/'
      preLoaderRoute: typeof AuthenticatedAssistenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/novo': {
      id: '/_authenticated/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof AuthenticatedChamadosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/novo': {
      id: '/_authenticated/base-conhecimento/novo'
      path: '/base-conhecimento/novo'
      fullPath: '/base-conhecimento/novo'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/$id': {
      id: '/_authenticated/base-conhecimento/$id'
      path: '/base-conhecimento/$id'
      fullPath: '/base-conhecimento/$id'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente/$conversaId': {
      id: '/_authenticated/assistente/$conversaId'
      path: '/assistente/$conversaId'
      fullPath: '/assistente/$conversaId'
      preLoaderRoute: typeof AuthenticatedAssistenteConversaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tipos-chamado': {
      id: '/_authenticated/admin/tipos-chamado'
      path: '/admin/tipos-chamado'
      fullPath: '/admin/tipos-chamado'
      preLoaderRoute: typeof AuthenticatedAdminTiposChamadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/segmentos': {
      id: '/_authenticated/admin/segmentos'
      path: '/admin/segmentos'
      fullPath: '/admin/segmentos'
      preLoaderRoute: typeof AuthenticatedAdminSegmentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/regras-atribuicao': {
      id: '/_authenticated/admin/regras-atribuicao'
      path: '/admin/regras-atribuicao'
      fullPath: '/admin/regras-atribuicao'
      preLoaderRoute: typeof AuthenticatedAdminRegrasAtribuicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/itsm-permissoes': {
      id: '/_authenticated/admin/itsm-permissoes'
      path: '/admin/itsm-permissoes'
      fullPath: '/admin/itsm-permissoes'
      preLoaderRoute: typeof AuthenticatedAdminItsmPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/grupos': {
      id: '/_authenticated/admin/grupos'
      path: '/admin/grupos'
      fullPath: '/admin/grupos'
      preLoaderRoute: typeof AuthenticatedAdminGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documentacao': {
      id: '/_authenticated/admin/documentacao'
      path: '/admin/documentacao'
      fullPath: '/admin/documentacao'
      preLoaderRoute: typeof AuthenticatedAdminDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/automacoes': {
      id: '/_authenticated/admin/automacoes'
      path: '/admin/automacoes'
      fullPath: '/admin/automacoes'
      preLoaderRoute: typeof AuthenticatedAdminAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/assistente': {
      id: '/_authenticated/admin/assistente'
      path: '/admin/assistente'
      fullPath: '/admin/assistente'
      preLoaderRoute: typeof AuthenticatedAdminAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/base-conhecimento/$id/editar': {
      id: '/_authenticated/base-conhecimento/$id/editar'
      path: '/editar'
      fullPath: '/base-conhecimento/$id/editar'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdEditarRouteImport
      parentRoute: typeof AuthenticatedBaseConhecimentoIdRoute
    }
  }
}

interface AuthenticatedBaseConhecimentoIdRouteChildren {
  AuthenticatedBaseConhecimentoIdEditarRoute: typeof AuthenticatedBaseConhecimentoIdEditarRoute
}

const AuthenticatedBaseConhecimentoIdRouteChildren: AuthenticatedBaseConhecimentoIdRouteChildren =
  {
    AuthenticatedBaseConhecimentoIdEditarRoute:
      AuthenticatedBaseConhecimentoIdEditarRoute,
  }

const AuthenticatedBaseConhecimentoIdRouteWithChildren =
  AuthenticatedBaseConhecimentoIdRoute._addFileChildren(
    AuthenticatedBaseConhecimentoIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedItsmAtivosRoute: typeof AuthenticatedItsmAtivosRoute
  AuthenticatedItsmAuditoriaRoute: typeof AuthenticatedItsmAuditoriaRoute
  AuthenticatedItsmAvancadoRoute: typeof AuthenticatedItsmAvancadoRoute
  AuthenticatedItsmConhecimentoRoute: typeof AuthenticatedItsmConhecimentoRoute
  AuthenticatedItsmGovernancaRoute: typeof AuthenticatedItsmGovernancaRoute
  AuthenticatedItsmMudancasRoute: typeof AuthenticatedItsmMudancasRoute
  AuthenticatedItsmProblemasRoute: typeof AuthenticatedItsmProblemasRoute
  AuthenticatedItsmRelacionamentosRoute: typeof AuthenticatedItsmRelacionamentosRoute
  AuthenticatedItsmServicosRoute: typeof AuthenticatedItsmServicosRoute
  AuthenticatedAdminAssistenteRoute: typeof AuthenticatedAdminAssistenteRoute
  AuthenticatedAdminAutomacoesRoute: typeof AuthenticatedAdminAutomacoesRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminDocumentacaoRoute: typeof AuthenticatedAdminDocumentacaoRoute
  AuthenticatedAdminGruposRoute: typeof AuthenticatedAdminGruposRoute
  AuthenticatedAdminItsmPermissoesRoute: typeof AuthenticatedAdminItsmPermissoesRoute
  AuthenticatedAdminRegrasAtribuicaoRoute: typeof AuthenticatedAdminRegrasAtribuicaoRoute
  AuthenticatedAdminSegmentosRoute: typeof AuthenticatedAdminSegmentosRoute
  AuthenticatedAdminTiposChamadoRoute: typeof AuthenticatedAdminTiposChamadoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAssistenteConversaIdRoute: typeof AuthenticatedAssistenteConversaIdRoute
  AuthenticatedBaseConhecimentoIdRoute: typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  AuthenticatedBaseConhecimentoNovoRoute: typeof AuthenticatedBaseConhecimentoNovoRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
  AuthenticatedChamadosNovoRoute: typeof AuthenticatedChamadosNovoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAssistenteIndexRoute: typeof AuthenticatedAssistenteIndexRoute
  AuthenticatedBaseConhecimentoIndexRoute: typeof AuthenticatedBaseConhecimentoIndexRoute
  AuthenticatedChamadosIndexRoute: typeof AuthenticatedChamadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedItsmAtivosRoute: AuthenticatedItsmAtivosRoute,
  AuthenticatedItsmAuditoriaRoute: AuthenticatedItsmAuditoriaRoute,
  AuthenticatedItsmAvancadoRoute: AuthenticatedItsmAvancadoRoute,
  AuthenticatedItsmConhecimentoRoute: AuthenticatedItsmConhecimentoRoute,
  AuthenticatedItsmGovernancaRoute: AuthenticatedItsmGovernancaRoute,
  AuthenticatedItsmMudancasRoute: AuthenticatedItsmMudancasRoute,
  AuthenticatedItsmProblemasRoute: AuthenticatedItsmProblemasRoute,
  AuthenticatedItsmRelacionamentosRoute: AuthenticatedItsmRelacionamentosRoute,
  AuthenticatedItsmServicosRoute: AuthenticatedItsmServicosRoute,
  AuthenticatedAdminAssistenteRoute: AuthenticatedAdminAssistenteRoute,
  AuthenticatedAdminAutomacoesRoute: AuthenticatedAdminAutomacoesRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminDocumentacaoRoute: AuthenticatedAdminDocumentacaoRoute,
  AuthenticatedAdminGruposRoute: AuthenticatedAdminGruposRoute,
  AuthenticatedAdminItsmPermissoesRoute: AuthenticatedAdminItsmPermissoesRoute,
  AuthenticatedAdminRegrasAtribuicaoRoute:
    AuthenticatedAdminRegrasAtribuicaoRoute,
  AuthenticatedAdminSegmentosRoute: AuthenticatedAdminSegmentosRoute,
  AuthenticatedAdminTiposChamadoRoute: AuthenticatedAdminTiposChamadoRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAssistenteConversaIdRoute:
    AuthenticatedAssistenteConversaIdRoute,
  AuthenticatedBaseConhecimentoIdRoute:
    AuthenticatedBaseConhecimentoIdRouteWithChildren,
  AuthenticatedBaseConhecimentoNovoRoute:
    AuthenticatedBaseConhecimentoNovoRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
  AuthenticatedChamadosNovoRoute: AuthenticatedChamadosNovoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAssistenteIndexRoute: AuthenticatedAssistenteIndexRoute,
  AuthenticatedBaseConhecimentoIndexRoute:
    AuthenticatedBaseConhecimentoIndexRoute,
  AuthenticatedChamadosIndexRoute: AuthenticatedChamadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAssistenteRoute: ApiAssistenteRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
